services:
  dbt:
    container_name: dbt
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
    networks:
      - app
    depends_on:
      - clickhouse
    entrypoint: ['sleep', 'infinity']

  clickhouse:
    container_name: dbt_clickhouse
    image: clickhouse/clickhouse-server:24.3.15.72  # lisbon palantir version
    environment:
      - CLICKHOUSE_USER=$CLICKHOUSE_USER
      - CLICKHOUSE_PASSWORD=$CLICKHOUSE_PASSWORD
    ports:
      - '8125:8123'
    networks:
      - app

networks:
  app:
    driver: bridge